version: '3'
services:
        postgres:
                image: postgres
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: password
                        POSTGRES_DB: db_scheduler
                ports:
                        - 25432:5432
                volumes:
                        - ./scheduler_postgres-db:/var/lib/postgresql/data
                restart: always
volumes:
        scheduler_postgres-db:
